### ISSUE TITLE
Recent Searches

### ISSUE THREAD

**Issue by adriamurphy** [searchspring/snap#417] opened 2022-03-21 22:17 UTC
Something that comes up fairly often is displaying a list of recent searches. Two places I have seen this feature:

1. Inside the Autocomplete.
2. Above search results.

Within Autocomplete, it would be nice to have the ability to display these at the same time as suggested terms.

**Comment by korgon** [comment] 2022-11-04 17:29
Duplicate of #671 - underway now.

**Closed by korgon** 2022-11-04 17:29 UTC
Labels: feature request
